name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: wal/setup-swift@v4
    - name: Get swift version
      run: swift --version # Swift 5.4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
